-- Tally v3 — production-ready schema (self-contained, separate DB from v1/v2).
--
-- =============================================================================
-- TABLE CONVENTION — every table follows it; keep it that way when adding one.
-- =============================================================================
--   id          CHAR(36) PRIMARY KEY     UUID, generated by the API (uuid4()).
--                                        Never an auto-increment: ids are stable
--                                        and stay valid across dumps/merges.
--   seq         BIGINT AUTO_INCREMENT    Insert order, and the ONLY thing lists
--                                        sort by. Never reused, never rewritten,
--                                        so an edit cannot reorder history.
--   timestamp   DATETIME                 When the thing happened in the real
--                                        world. This is what the UI displays and
--                                        groups by day; an edit preserves it.
--   created_at  TIMESTAMP                Row written. Audit only.
--   updated_at  TIMESTAMP                Row last changed. Audit only.
--
-- Editing NEVER deletes and re-inserts: a row is UPDATEd in place so id, seq and
-- timestamp survive and only updated_at moves. That keeps history order, the
-- running stock chain and the "last price" columns chronological.
--
-- MySQL allows one auto-increment column and it must be a key, hence the
-- `UNIQUE KEY uq_<t>_seq (seq)` on every table alongside the UUID primary key.
--
-- Exceptions, deliberate:
--   * sessions        — keyed by the opaque bearer token; no seq/timestamp, it
--                       is transient auth state, not business history.
--   * product_materials — a pure join table (composite PK, no identity of its
--                       own); carries seq/created_at only.
-- =============================================================================
--
-- Design principle: every "calculative" value is DENORMALISED and kept up to date on
-- write (insert/update/delete) so the UI only ever needs a plain SELECT — no aggregation
-- at read time. See v3/backend/index.php recomputeCustomer()/recomputeProduct().
--
-- Time convention: ALL time columns (DATE/DATETIME/TIMESTAMP) store UTC. The API
-- connection runs with `SET time_zone = '+00:00'` and PHP uses UTC (config.php), so
-- CURRENT_TIMESTAMP/NOW() and any written value are UTC. The frontend renders them in
-- the viewer's local zone (v3/src/lib/format.ts parseServerTime()).

CREATE DATABASE IF NOT EXISTS tally_v3
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tally_v3;

-- Drop in dependency order so the file is re-runnable.
DROP TABLE IF EXISTS operation_cost_entries;
DROP TABLE IF EXISTS operation_costs;
DROP TABLE IF EXISTS personal_transactions;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS product_materials;
DROP TABLE IF EXISTS material_transactions;
DROP TABLE IF EXISTS product_transactions;
DROP TABLE IF EXISTS customer_payment_allocations;
DROP TABLE IF EXISTS customer_items;
DROP TABLE IF EXISTS customer_balance_history;
DROP TABLE IF EXISTS materials;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS users;

-- ---------------------------------------------------------------------------
-- Users — one row per Google account. Identity comes from Google Sign-In:
-- google_id is the token's `sub` claim (stable per account); email/name/picture
-- are refreshed from the ID token on every login.
-- `timestamp` is the sign-up moment.
--
-- theme/language are the account's display preferences, so a signed-in user
-- finds the app as they left it on any device. The client still keeps a cookie
-- copy (it is what paints the first frame, and it is all a signed-out visitor
-- has); on login the row below wins.
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id         CHAR(36)     NOT NULL PRIMARY KEY,
    seq        BIGINT       NOT NULL AUTO_INCREMENT,
    google_id  VARCHAR(255) NOT NULL,               -- Google ID-token `sub`
    email      VARCHAR(255) NOT NULL DEFAULT '',
    name       VARCHAR(255) NOT NULL DEFAULT '',
    picture    VARCHAR(512) NOT NULL DEFAULT '',
    theme      ENUM('system','light','dark') NOT NULL DEFAULT 'system',
    language   ENUM('en','bn')               NOT NULL DEFAULT 'en',
    timestamp  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_users_seq (seq),
    CONSTRAINT uq_users_google UNIQUE (google_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Books (a "store") — owned by exactly one user; a user can have many books.
-- ---------------------------------------------------------------------------
CREATE TABLE books (
    id         CHAR(36)     NOT NULL PRIMARY KEY,
    seq        BIGINT       NOT NULL AUTO_INCREMENT,
    user_id    CHAR(36)     NOT NULL,               -- owner (users.id)
    name       VARCHAR(100) NOT NULL,
    -- 'store' books use products + customer balances; 'personal' books use transactions.
    -- The UI renders a type-based icon (no per-book logo).
    type       ENUM('store','personal') NOT NULL DEFAULT 'store',
    -- How far a customer of this book is allowed to run: the most they may owe,
    -- and how long a debt may stand before it is called overdue. Book-wide, not
    -- per customer — a shop keeps one rule, not one per name. NULL means that
    -- half is not policed. Neither is enforced: exceeding one raises a warning
    -- the user is free to overrule, because a shopkeeper who has decided to let
    -- a regular go further should not be stopped by their own reminder.
    credit_limit DECIMAL(14,2) NULL,
    credit_days  INT           NULL,
    timestamp  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_books_seq (seq),
    CONSTRAINT fk_books_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_books_user ON books(user_id, seq);

-- ---------------------------------------------------------------------------
-- Sessions — opaque bearer tokens issued on login (revocable, server-side).
-- The frontend stores the token and sends it as `Authorization: Bearer <token>`.
-- CONVENTION EXCEPTION: keyed by the token itself; transient auth state with no
-- business timestamp and nothing that lists it, so it carries no seq.
-- ---------------------------------------------------------------------------
CREATE TABLE sessions (
    token      CHAR(64)  NOT NULL PRIMARY KEY,       -- random 32-byte hex
    user_id    CHAR(36)  NOT NULL,
    expires_at DATETIME  NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_sessions_user ON sessions(user_id);

-- ---------------------------------------------------------------------------
-- Customers — names are NOT unique (a nickname disambiguates).
-- total_balance / transaction_count / last_transaction_time are DENORMALISED,
-- and so are the figures the tab sheet shows:
--   cash_balance    cash still outstanding (+ paid ahead, - still borrowed)
--   items_due       goods taken and not paid for
--   total_unpaid    every debt ever run up, whatever has since been paid
--   total_paid_back every payment ever made, cash and goods together
-- The first two are what STANDS today and always sum to total_balance
-- (cash_balance - items_due); the last two are lifetime running totals and do
-- not. All of them are rewritten by recomputeCustomer(), which walks the ledger
-- and settles each payment against what it is already on record as having paid
-- (customer_payment_allocations), then the line it was aimed at, then borrowed
-- cash oldest first, then goods oldest first.
-- ---------------------------------------------------------------------------
CREATE TABLE customers (
    id                    CHAR(36)      NOT NULL PRIMARY KEY,
    seq                   BIGINT        NOT NULL AUTO_INCREMENT,
    book_id               CHAR(36)      NOT NULL,
    name                  VARCHAR(100)  NOT NULL,
    nickname              VARCHAR(100)  NOT NULL DEFAULT '',
    phone                 VARCHAR(30)   NOT NULL DEFAULT '',
    address               VARCHAR(255)  NOT NULL DEFAULT '',
    total_balance         DECIMAL(14,2) NOT NULL DEFAULT 0.00,  -- + advance paid, - owed
    cash_balance          DECIMAL(14,2) NOT NULL DEFAULT 0.00,  -- + paid ahead, - borrowed
    items_due             DECIMAL(14,2) NOT NULL DEFAULT 0.00,  -- always >= 0
    total_unpaid          DECIMAL(14,2) NOT NULL DEFAULT 0.00,  -- lifetime, always >= 0
    total_paid_back       DECIMAL(14,2) NOT NULL DEFAULT 0.00,  -- lifetime, always >= 0
    transaction_count     INT           NOT NULL DEFAULT 0,
    last_transaction_time DATETIME      NULL,
    -- When the customer's CURRENT unbroken run of owing money began — the entry
    -- that last took the balance negative and never came back. NULL whenever the
    -- balance is square or ahead. Clearing the debt and running up a new one
    -- starts the clock again, which is what "paid back in time" has to mean:
    -- age is a property of the debt standing now, not of the account.
    debt_since            DATETIME      NULL,
    timestamp             DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at            TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_customers_seq (seq),
    CONSTRAINT fk_customers_book FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    -- Same name is allowed only when the nickname differs; blocks exact duplicates.
    CONSTRAINT uq_customer_identity UNIQUE (book_id, name, nickname)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_customers_book_name     ON customers(book_id, name);
CREATE INDEX idx_customers_book_last_txn ON customers(book_id, last_transaction_time DESC);

-- ---------------------------------------------------------------------------
-- Customer balance history — one paid/unpaid entry. This is the whole money
-- ledger: nothing a customer owes or pays exists outside it.
-- signed_amount / balance_after are precomputed snapshots for the history view.
-- `timestamp` is when the money moved; editing an entry keeps it, so the running
-- balance_after chain (walked in seq order) stays meaningful.
--
-- `source` says what kind of entry it is, and therefore how it may be edited:
--   'cash'  plain money — borrowed (unpaid) or handed back (paid). A repayment
--           is UNTARGETED: the waterfall in recomputeCustomer() puts it against
--           the borrowed cash first and spreads whatever is left over the open
--           item lines, oldest first, part-paying the one it runs out on.
--   'item'  goods. An 'unpaid' one is a taking (written beside a sale row and a
--           customer_items line); a 'paid' one is a payment TARGETED at that
--           line (the Paid button). Editing a taking re-quantifies the goods, so
--           the API rewrites the sale — and therefore stock — along with it.
-- The item snapshot columns (customer_item_id, item_name, quantity_type,
-- quantity, price_per_unit) are NULL on cash entries; together they let the
-- entry render and be edited without touching the goods tables. customer_item_id carries no FK on
-- purpose: the line is deleted the moment it is fully settled, and the id must
-- survive that so the entry still knows which line it settled (same reasoning
-- as product_transactions.customer_item_id).
-- ---------------------------------------------------------------------------
CREATE TABLE customer_balance_history (
    id               CHAR(36)              NOT NULL PRIMARY KEY,
    seq              BIGINT                NOT NULL AUTO_INCREMENT,
    customer_id      CHAR(36)              NOT NULL,
    book_id          CHAR(36)              NOT NULL,
    amount           DECIMAL(14,2)         NOT NULL,            -- always positive
    type             ENUM('paid','unpaid') NOT NULL,
    source           ENUM('cash','item')   NOT NULL DEFAULT 'cash',
    signed_amount    DECIMAL(14,2)         NOT NULL,            -- +amount paid / -amount unpaid
    balance_after    DECIMAL(14,2)         NOT NULL DEFAULT 0,  -- running balance after this entry
    reason           VARCHAR(255)          NULL,
    customer_item_id CHAR(36)              NULL,                -- item entries: the line taken/settled
    item_name        VARCHAR(100)          NULL,                -- item entries: snapshot
    quantity_type    VARCHAR(50)           NULL,                -- item entries: snapshot
    quantity         DECIMAL(14,3)         NULL,                -- item entries: units this entry moved
    price_per_unit   DECIMAL(14,2)         NULL,                -- item entries: agreed at the time
    timestamp        DATETIME              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at       TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP             DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_cbh_seq (seq),
    CONSTRAINT fk_cbh_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
    CONSTRAINT fk_cbh_book     FOREIGN KEY (book_id)     REFERENCES books(id)     ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_cbh_customer_seq ON customer_balance_history(customer_id, seq DESC);
-- recomputeCustomer() sums the cash half and the paid half per customer.
CREATE INDEX idx_cbh_customer_source ON customer_balance_history(customer_id, source);

-- ---------------------------------------------------------------------------
-- Products — derived stock is DENORMALISED onto the row (current_stock, totals,
-- last prices, stock_value, last_transaction_time) so listing needs no
-- JOIN/aggregation.
-- image_url is MEDIUMTEXT to hold base64 data URLs.
-- ---------------------------------------------------------------------------
CREATE TABLE products (
    id                    CHAR(36)      NOT NULL PRIMARY KEY,
    seq                   BIGINT        NOT NULL AUTO_INCREMENT,
    book_id               CHAR(36)      NOT NULL,
    name                  VARCHAR(100)  NOT NULL,
    quantity_type         VARCHAR(50)   NOT NULL DEFAULT 'piece',
    -- 'ready_made' products are bought and resold (one buying price per stock-in),
    -- so their stock/purchase columns are derived from stock-in + sale entries.
    -- 'manufacture' products are produced from linked raw materials (product_materials)
    -- and are SALE-ONLY: there is no stock-in. Because a single sale's material
    -- consumption is unknown until analytics lands, current_stock/total_stock_in/
    -- last_purchase_price/stock_value stay NULL for them; only sale-derived
    -- columns are filled.
    product_type          ENUM('ready_made','manufacture') NOT NULL DEFAULT 'ready_made',
    image_url             MEDIUMTEXT    NULL,
    current_stock         DECIMAL(14,3) NULL,          -- NULL for manufacture (analytics later)
    total_stock_in        DECIMAL(14,3) NULL,          -- NULL for manufacture (analytics later)
    total_stock_out       DECIMAL(14,3) NOT NULL DEFAULT 0,
    last_purchase_price   DECIMAL(14,2) NULL,
    last_sale_price       DECIMAL(14,2) NULL,
    -- What the stock in hand cost, valued FIFO. Successive stock-ins arrive at
    -- different prices, so the stock cannot be priced by any single one of them:
    -- the oldest units are the ones that have left, so what is still on the shelf
    -- is what came in last, and current_stock is filled from the newest stock-in
    -- backwards. Empty (or overdrawn, which is a miscount rather than a debt) is
    -- worth 0. NULL for manufacture, which holds no stock of its own.
    -- Rewritten by recomputeProduct() — never written directly.
    stock_value           DECIMAL(14,2) NULL,          -- NULL for manufacture (analytics later)
    transaction_count     INT           NOT NULL DEFAULT 0,
    last_transaction_time DATETIME      NULL,
    timestamp             DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at            TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_products_seq (seq),
    CONSTRAINT fk_products_book FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    -- A product name is unique within a book. (Also serves book_id+name lookups
    -- and the "ORDER BY name" listing, so no separate index is needed.)
    CONSTRAINT uq_product_identity UNIQUE (book_id, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_products_book_last_txn ON products(book_id, last_transaction_time DESC);

-- ---------------------------------------------------------------------------
-- Product transactions — stock in / sale. total_amount is a precomputed running
-- value. stock_after is the running stock for ready-made products; it is NULL
-- for manufacture products (sale-only, stock unknown until analytics lands).
--
-- `timestamp` is when the goods moved. History lists and the running stock chain
-- both walk `seq`, and an edit UPDATEs the row, so neither an edit nor a later
-- entry can reorder what came before.
--
-- customer_id marks a sale that went onto a customer's tab instead of over the
-- counter. It is the goods' half of that sale; the debt itself lives in
-- customer_balance_history and what is still owed in customer_items.
--
-- customer_item_id points at the exact outstanding line this sale created (or
-- merged into). Settling in full deletes that line, so a dangling id is how the
-- history knows the sale has since been paid for — deliberately NOT a foreign
-- key, or the link would be nulled and the pill could never tell "paid" from
-- "never on a tab". Re-taking the same goods later opens a NEW line, so the old
-- sale stays paid instead of lighting up again.
--
-- customer_history_id names the debt entry the sale booked. Editing the sale
-- from the product's own history rewrites that entry through this link, so the
-- goods, the outstanding line and the customer's balance stay in step.
-- ---------------------------------------------------------------------------
CREATE TABLE product_transactions (
    id                  CHAR(36)             NOT NULL PRIMARY KEY,
    seq                 BIGINT               NOT NULL AUTO_INCREMENT,
    product_id          CHAR(36)             NOT NULL,
    book_id             CHAR(36)             NOT NULL,
    type                ENUM('stock','sale') NOT NULL,
    quantity            DECIMAL(14,3)        NOT NULL,
    price_per_unit      DECIMAL(14,2)        NOT NULL,
    total_amount        DECIMAL(14,2)        NOT NULL,   -- quantity * price_per_unit
    stock_after         DECIMAL(14,3)        NULL,       -- running stock (NULL for manufacture)
    customer_id         CHAR(36)             NULL,       -- set = sold on this customer's tab
    customer_item_id    CHAR(36)             NULL,       -- the tab line these goods went on
    customer_history_id CHAR(36)             NULL,       -- the debt entry this sale booked
    note                VARCHAR(255)         NULL,
    timestamp           DATETIME             NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at          TIMESTAMP            DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP            DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_pt_seq (seq),
    CONSTRAINT fk_pt_product  FOREIGN KEY (product_id)  REFERENCES products(id)  ON DELETE CASCADE,
    CONSTRAINT fk_pt_book     FOREIGN KEY (book_id)     REFERENCES books(id)     ON DELETE CASCADE,
    CONSTRAINT fk_pt_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_pt_product ON product_transactions(product_id, seq DESC);
-- Reverse lookup from the customer's ledger: which sale a debt entry booked, so
-- editing that entry can move the goods too (see tabSaleForEntry()).
CREATE INDEX idx_pt_customer_history ON product_transactions(customer_history_id);

-- ---------------------------------------------------------------------------
-- Categories (personal books) — income/expense buckets. transaction_count is
-- DENORMALISED on write so the manager needs no aggregation at read time.
-- ---------------------------------------------------------------------------
CREATE TABLE categories (
    id                CHAR(36)      NOT NULL PRIMARY KEY,
    seq               BIGINT        NOT NULL AUTO_INCREMENT,
    book_id           CHAR(36)      NOT NULL,
    name              VARCHAR(100)  NOT NULL,
    details           VARCHAR(255)  NOT NULL DEFAULT '',
    type              ENUM('income','expense') NOT NULL,
    transaction_count INT           NOT NULL DEFAULT 0,   -- denormalised
    timestamp         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_categories_seq (seq),
    CONSTRAINT fk_categories_book FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    -- A category name is unique per type within a book.
    CONSTRAINT uq_category_identity UNIQUE (book_id, type, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_categories_book_type ON categories(book_id, type, name);

-- ---------------------------------------------------------------------------
-- Personal transactions (personal books) — income/expense entries. category_name
-- is a DENORMALISED snapshot so the list needs no JOIN; signed_amount (+income /
-- -expense) makes the summary a trivial sum. On category delete the FK nulls the
-- link but the row keeps its category_name label.
-- ---------------------------------------------------------------------------
CREATE TABLE personal_transactions (
    id            CHAR(36)      NOT NULL PRIMARY KEY,
    seq           BIGINT        NOT NULL AUTO_INCREMENT,
    book_id       CHAR(36)      NOT NULL,
    category_id   CHAR(36)      NULL,
    category_name VARCHAR(100)  NOT NULL DEFAULT '',   -- denormalised snapshot
    type          ENUM('income','expense') NOT NULL,
    note          VARCHAR(255)  NOT NULL DEFAULT '',
    amount        DECIMAL(14,2) NOT NULL,              -- always positive
    signed_amount DECIMAL(14,2) NOT NULL,              -- +income / -expense
    timestamp     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_ptx_seq (seq),
    CONSTRAINT fk_ptx_book     FOREIGN KEY (book_id)     REFERENCES books(id)      ON DELETE CASCADE,
    CONSTRAINT fk_ptx_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_ptx_book_seq ON personal_transactions(book_id, seq DESC);
CREATE INDEX idx_ptx_category ON personal_transactions(category_id);

-- ---------------------------------------------------------------------------
-- Materials (store books) — raw stock tracked independently of products (not
-- linked to any product yet). Modelled on `products` (ready-made): a stock-in
-- carries one buying price, a sale one selling price. Derived stock/totals/last
-- prices/stock_value are DENORMALISED onto the row (see recomputeMaterial()).
-- image_url is MEDIUMTEXT to hold base64 data URLs.
-- ---------------------------------------------------------------------------
CREATE TABLE materials (
    id                    CHAR(36)      NOT NULL PRIMARY KEY,
    seq                   BIGINT        NOT NULL AUTO_INCREMENT,
    book_id               CHAR(36)      NOT NULL,
    name                  VARCHAR(100)  NOT NULL,
    quantity_type         VARCHAR(50)   NOT NULL DEFAULT 'piece',
    image_url             MEDIUMTEXT    NULL,
    current_stock         DECIMAL(14,3) NOT NULL DEFAULT 0,
    total_stock_in        DECIMAL(14,3) NOT NULL DEFAULT 0,
    total_stock_out       DECIMAL(14,3) NOT NULL DEFAULT 0,
    last_purchase_price   DECIMAL(14,2) NULL,
    last_sale_price       DECIMAL(14,2) NULL,
    -- What the stock in hand cost, valued FIFO — see the products column of the
    -- same name for why a single price cannot answer it. A material always holds
    -- its own stock, so this is 0 rather than NULL when there is none.
    -- Rewritten by recomputeMaterial() — never written directly.
    stock_value           DECIMAL(14,2) NOT NULL DEFAULT 0,
    transaction_count     INT           NOT NULL DEFAULT 0,
    last_transaction_time DATETIME      NULL,
    timestamp             DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at            TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_materials_seq (seq),
    CONSTRAINT fk_materials_book FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    -- A material name is unique within a book (also serves the "ORDER BY name" listing).
    CONSTRAINT uq_material_identity UNIQUE (book_id, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_materials_book_last_txn ON materials(book_id, last_transaction_time DESC);

-- ---------------------------------------------------------------------------
-- Material transactions — stock in / sale / used. For stock-in and sale the
-- user enters the total price and price_per_unit is the derived per-unit cost
-- (total_amount / quantity). A 'used' entry is consumption only: it lowers
-- stock with no price (price_per_unit and total_amount are 0). total_amount and
-- stock_after are precomputed running values (recomputeMaterial()).
-- The customer_* links mirror product_transactions — see the comment there.
-- ---------------------------------------------------------------------------
CREATE TABLE material_transactions (
    id                  CHAR(36)                    NOT NULL PRIMARY KEY,
    seq                 BIGINT                      NOT NULL AUTO_INCREMENT,
    material_id         CHAR(36)                    NOT NULL,
    book_id             CHAR(36)                    NOT NULL,
    type                ENUM('stock','sale','used') NOT NULL,
    quantity            DECIMAL(14,3)               NOT NULL,
    price_per_unit      DECIMAL(14,2)               NOT NULL,   -- derived: total_amount / quantity (0 for 'used')
    total_amount        DECIMAL(14,2)               NOT NULL,   -- entered total price (0 for 'used')
    stock_after         DECIMAL(14,3)               NOT NULL DEFAULT 0,
    customer_id         CHAR(36)                    NULL,       -- set = sold on this customer's tab
    customer_item_id    CHAR(36)                    NULL,       -- the tab line these goods went on
    customer_history_id CHAR(36)                    NULL,       -- the debt entry this sale booked
    note                VARCHAR(255)                NULL,
    timestamp           DATETIME                    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at          TIMESTAMP                   DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP                   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_mt_seq (seq),
    CONSTRAINT fk_mt_material FOREIGN KEY (material_id) REFERENCES materials(id) ON DELETE CASCADE,
    CONSTRAINT fk_mt_book     FOREIGN KEY (book_id)     REFERENCES books(id)     ON DELETE CASCADE,
    CONSTRAINT fk_mt_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_mt_material ON material_transactions(material_id, seq DESC);
-- Same reverse lookup as product_transactions.
CREATE INDEX idx_mt_customer_history ON material_transactions(customer_history_id);

-- ---------------------------------------------------------------------------
-- Product ↔ material links (manufacture products) — the many-to-many relation
-- of which materials a manufacture product is made from. One product links many
-- materials; one material is reusable across many products. This is the ONLY
-- coupling between products and materials: consumption per sale is deferred to a
-- future analytics feature. Rows cascade-delete with either side.
--
-- CONVENTION EXCEPTION: a pure join table. The composite key IS its identity, so
-- there is no UUID and no business timestamp; seq only records link order.
-- ---------------------------------------------------------------------------
CREATE TABLE product_materials (
    product_id  CHAR(36)  NOT NULL,
    material_id CHAR(36)  NOT NULL,
    book_id     CHAR(36)  NOT NULL,
    seq         BIGINT    NOT NULL AUTO_INCREMENT,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    -- Composite PK enforces uniqueness and serves the "materials of a product" lookup.
    PRIMARY KEY (product_id, material_id),
    UNIQUE KEY uq_pm_seq (seq),
    CONSTRAINT fk_pm_product  FOREIGN KEY (product_id)  REFERENCES products(id)  ON DELETE CASCADE,
    CONSTRAINT fk_pm_material FOREIGN KEY (material_id) REFERENCES materials(id) ON DELETE CASCADE,
    CONSTRAINT fk_pm_book     FOREIGN KEY (book_id)     REFERENCES books(id)     ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Reverse lookup: every product a given material is used in (a material delete
-- cascades here; analytics will read this direction too).
CREATE INDEX idx_pm_material ON product_materials(material_id);

-- ---------------------------------------------------------------------------
-- Customer items — the goods a customer has taken on their tab.
--
-- `quantity` is what was TAKEN and never changes on payment; `paid_amount` is
-- how much money has since been put against the line, so a line is cleared when
-- paid_amount >= total_amount and partly paid anywhere in between. Rows are NOT
-- deleted when they are paid off — they are deleted only when the sale behind
-- them is. The goods left the shop when the line was written, so paying for
-- them never touches stock.
--
-- paid_amount is DENORMALISED and never written directly: recomputeCustomer()
-- replays the whole ledger and re-derives every line's share (see the payment
-- waterfall described there). Nothing else may set it.
--
-- Taking an item writes three things in one transaction (see the
-- POST /customers/{id}/items handler):
--   1. a real 'sale' row on product_transactions / material_transactions
--      (so stock and sale totals stay correct — this IS the sale),
--   2. this row (or a bump to a matching one),
--   3. an 'unpaid' customer_balance_history entry for quantity * price_per_unit.
-- Paying writes a 'paid' history entry — targeted at one line (the Paid button)
-- or untargeted cash, which the waterfall spreads. The money ledger therefore
-- stays customer_balance_history alone; this table only tracks which goods are
-- outstanding and how far each has been covered.
--
-- product_id / material_id: exactly one is set, matching item_type. Both are
-- nullable so deleting a product/material leaves the debt intact — item_name and
-- quantity_type are snapshots taken at the time, so the row still renders.
-- ---------------------------------------------------------------------------
CREATE TABLE customer_items (
    id             CHAR(36)      NOT NULL PRIMARY KEY,
    seq            BIGINT        NOT NULL AUTO_INCREMENT,
    customer_id    CHAR(36)      NOT NULL,
    book_id        CHAR(36)      NOT NULL,
    item_type      ENUM('product','material') NOT NULL,
    product_id     CHAR(36)      NULL,
    material_id    CHAR(36)      NULL,
    item_name      VARCHAR(100)  NOT NULL,                 -- snapshot
    quantity_type  VARCHAR(50)   NOT NULL DEFAULT 'piece', -- snapshot
    quantity       DECIMAL(14,3) NOT NULL,                 -- units taken
    price_per_unit DECIMAL(14,2) NOT NULL,                 -- agreed at the time
    total_amount   DECIMAL(14,2) NOT NULL,                 -- quantity * price_per_unit
    paid_amount    DECIMAL(14,2) NOT NULL DEFAULT 0.00,    -- covered so far; 0 .. total_amount
    timestamp      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_ci_seq (seq),
    CONSTRAINT fk_ci_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
    CONSTRAINT fk_ci_book     FOREIGN KEY (book_id)     REFERENCES books(id)     ON DELETE CASCADE,
    CONSTRAINT fk_ci_product  FOREIGN KEY (product_id)  REFERENCES products(id)  ON DELETE SET NULL,
    CONSTRAINT fk_ci_material FOREIGN KEY (material_id) REFERENCES materials(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_ci_customer_seq ON customer_items(customer_id, seq DESC);

-- ---------------------------------------------------------------------------
-- Customer payment allocations — which debt each payment actually settled.
--
-- The ledger alone cannot answer that. recomputeCustomer() replays it from the
-- start, so without a record the waterfall re-decides EVERY payment on every
-- replay — and deleting one entry lets a later payment reach back and cover a
-- debt it never covered at the time. Deleting a settlement would then move the
-- debt to a different pile rather than reopening the goods it paid for, which
-- is not an undo.
--
-- So each payment's share is written down as it is made. A replay honours what
-- is on record first and only decides the remainder, which makes deleting an
-- entry an exact reversal: the rows for that payment go with it (FK cascade)
-- and every other payment stays where it was.
--
-- The rows are DERIVED — recomputeCustomer() rewrites a customer's whole set on
-- every replay — so they are a record, never a second source of truth. Dropping
-- the table's contents costs only the history of who-paid-what, and the next
-- replay refills it from the waterfall.
--
-- debt_id is polymorphic on debt_kind and carries no FK:
--   'cash'  a customer_balance_history row (type='unpaid', source='cash')
--   'item'  a customer_items line (however many takings were merged onto it)
-- A row whose debt has since been deleted is simply not re-inserted.
-- ---------------------------------------------------------------------------
CREATE TABLE customer_payment_allocations (
    id          CHAR(36)            NOT NULL PRIMARY KEY,
    seq         BIGINT              NOT NULL AUTO_INCREMENT,  -- replay order
    customer_id CHAR(36)            NOT NULL,
    book_id     CHAR(36)            NOT NULL,
    payment_id  CHAR(36)            NOT NULL,   -- customer_balance_history, type='paid'
    debt_kind   ENUM('cash','item') NOT NULL,
    debt_id     CHAR(36)            NOT NULL,   -- see above; no FK on purpose
    amount      DECIMAL(14,2)       NOT NULL,   -- always positive
    created_at  TIMESTAMP           DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP           DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_cpa_seq (seq),
    -- One payment covers a given debt once; the replay sums before it writes.
    UNIQUE KEY uq_cpa_pair (payment_id, debt_kind, debt_id),
    CONSTRAINT fk_cpa_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
    CONSTRAINT fk_cpa_book     FOREIGN KEY (book_id)     REFERENCES books(id)     ON DELETE CASCADE,
    -- Deleting a payment entry drops what it paid for, which is what reopens the
    -- debt it had covered. This is the undo.
    CONSTRAINT fk_cpa_payment  FOREIGN KEY (payment_id)
        REFERENCES customer_balance_history(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- The replay reads a customer's whole set in seq order.
CREATE INDEX idx_cpa_customer_seq ON customer_payment_allocations(customer_id, seq);
CREATE INDEX idx_cpa_debt         ON customer_payment_allocations(debt_kind, debt_id);

-- ---------------------------------------------------------------------------
-- Operation costs (store books) — a named recurring cost (reason) with a
-- current amount + note. There is no stock/sale action; instead every add/edit
-- appends an immutable snapshot to operation_cost_entries, so the row keeps a
-- full amount history. The parent's `amount` mirrors the latest snapshot and
-- entry_count/last_entry_time are DENORMALISED (see recomputeOperationCost()).
-- ---------------------------------------------------------------------------
CREATE TABLE operation_costs (
    id              CHAR(36)      NOT NULL PRIMARY KEY,
    seq             BIGINT        NOT NULL AUTO_INCREMENT,
    book_id         CHAR(36)      NOT NULL,
    reason          VARCHAR(100)  NOT NULL,
    note            VARCHAR(255)  NOT NULL DEFAULT '',
    amount          DECIMAL(14,2) NOT NULL DEFAULT 0,   -- current (latest) amount
    entry_count     INT           NOT NULL DEFAULT 0,   -- denormalised
    last_entry_time DATETIME      NULL,
    timestamp       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_oc_seq (seq),
    CONSTRAINT fk_operation_costs_book FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    -- A reason is unique within a book (the amount history captures changes over time).
    CONSTRAINT uq_operation_identity UNIQUE (book_id, reason)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_operation_costs_book ON operation_costs(book_id, last_entry_time DESC);

-- ---------------------------------------------------------------------------
-- Operation cost entries — one amount snapshot per add/edit of an operation
-- cost. note is a snapshot at entry time so history renders as it was.
-- ---------------------------------------------------------------------------
CREATE TABLE operation_cost_entries (
    id                CHAR(36)      NOT NULL PRIMARY KEY,
    seq               BIGINT        NOT NULL AUTO_INCREMENT,
    operation_cost_id CHAR(36)      NOT NULL,
    book_id           CHAR(36)      NOT NULL,
    amount            DECIMAL(14,2) NOT NULL,
    note              VARCHAR(255)  NULL,
    timestamp         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_oce_seq (seq),
    CONSTRAINT fk_oce_operation FOREIGN KEY (operation_cost_id) REFERENCES operation_costs(id) ON DELETE CASCADE,
    CONSTRAINT fk_oce_book      FOREIGN KEY (book_id)           REFERENCES books(id)           ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_oce_operation_seq ON operation_cost_entries(operation_cost_id, seq DESC);
